### ISSUE TITLE
corecrt_wstdio.h 找不到标识符

### ISSUE THREAD

**Issue by sftt** [Chuyu-Team/VC-LTL#1]
请问没有预编译头的跨平台开源项目怎么#include<_msvcrt.h/cpp>？
我试着加在main所在cpp的最前面，编译阶段出错：
...\VC-LTL\VC140\corecrt_wstdio.h(1061): error C3861: “_vscwprintf_l”: 找不到标识符
...\VC-LTL\VC140\corecrt_wstdio.h(1061): error C3861: “_vswprintf_l”: 找不到标识符
...\VC-LTL\VC140\corecrt_wstdio.h(1163): error C3861: “_vscwprintf_l”: 找不到标识符
...\VC-LTL\VC140\corecrt_wstdio.h(1163): error C3861: “_vswprintf_l”: 找不到标识符
...\VC-LTL\VC140\corecrt_wstdio.h(1267): error C3861: “_vscwprintf_l”: 找不到标识符
请问这些函数是在哪个.h里#include的？
谢谢
尝试编译的工程：https://github.com/schnaader/precomp-cpp

**Comment by mingkuang-Chuyu** [comment]
Hi~ 你可以在最顶级的 .h 文件的开头添加 #include<_msvcrt.h>
 
然后在任意cpp中 添加 #include<_msvcrt.cpp>
 
 
我目测 precomp.h 以及 precomp.cpp中添加就可以了
 
 
 
即可，另外Windows SDK需要调整为WIndows 10，更低版本SDK没有进行适配处理

 
Date: Mon, 20 Jun 2016 19:25:29 -0700

**Comment by sftt** [comment]
> Windows SDK需要调整为WIndows 10

在Win7里面也需要安装WIndows 10 SDK么？这样编译出来的exe是否只有Win10才能运行？

> 然后在任意cpp中 添加 #include<_msvcrt.cpp>

是说随便选一个cpp添加就行了么？
还有上述工程里的contrib/zlib/ 之类第三方库都是项目需要编译的，并且没有依赖precomp.h
而precomp.cpp在之前已经导入了很多包，比如#include "contrib/zlib/zlib.h"
和<stdio.h>等系统包，之后才#include "precomp.h"，<_msvcrt.h>是否需要加在最前面？

谢谢

**Comment by mingkuang-Chuyu** [comment]
ltl已经改进了引用方式，降低了库使用难度，解决了此类问题。
新版本ltl无需引用任何文件即可使用。
