### ISSUE TITLE
VS2017 导入ltlvcrtWinXp.props配置之后Release编译程序失败

### ISSUE THREAD

**Issue by JohnWins** [Chuyu-Team/VC-LTL#11]
错误报告：
1>已完成代码的生成
1>vc141.lib(loadcfg.obj) : error LNK2001: 无法解析的外部符号 __guard_ss_verify_failure
1>vc141.lib(guard_support.obj) : error LNK2001: 无法解析的外部符号 __guard_ss_verify_failure_default
1>vc141.lib(guard_support.obj) : error LNK2001: 无法解析的外部符号 __guard_ss_verify_sp_default

**Comment by JohnWins** [comment]
增加：
Win32编译通过
 x64编译失败，

**Comment by mingkuang-Chuyu** [comment]
建议你提供工程，因为本地正常。

**Comment by mingkuang-Chuyu** [comment]
关闭此问题，用户长时间无反应，另外本地64位工程，均正常使用__guard_ss_verify_failure，__guard_ss_verify_failure_default以及__guard_ss_verify_sp_default。

**Comment by sgf** [comment]
XP 真的 可以放弃了。。。。
