### ISSUE TITLE
依然无法编译icu，还有打包lib建议不要使用中文路径如“D:\用户数据\Documents\”

### ISSUE THREAD

**Issue by sonyps5201314** [Chuyu-Team/VC-LTL#12]
1>------ 已启动生成: 项目: common, 配置: Release Win32 ------
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1189,5): warning MSB8012: TargetPath(N:\Open_Code\icu\icu4c\source\common\.\..\..\lib\common.dll) does not match the Linker's OutputFile property value (N:\Open_Code\icu\icu4c\bin\icuuc60.dll). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1191,5): warning MSB8012: TargetName(common) does not match the Linker's OutputFile property value (icuuc60). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
1>vc2013_crt_misc.obj : 找到 MSIL .netmodule 或使用 /GL 编译的模块；正在使用 /LTCG 重新启动链接；将 /LTCG 添加到链接命令行以改进链接器性能
1>  正在创建库 ..\..\lib\icuuc.lib 和对象 ..\..\lib\icuuc.exp
1>std_type_info.obj : error LNK2001: 无法解析的外部符号 __free_base
1>std_type_info.obj : error LNK2001: 无法解析的外部符号 __malloc_base
1>putil.obj : error LNK2001: 无法解析的外部符号 __imp____timezone
1>putil.obj : error LNK2001: 无法解析的外部符号 __imp____tzname
1>putil.obj : error LNK2001: 无法解析的外部符号 __imp____stdio_common_vsprintf
1>uloc.obj : error LNK2001: 无法解析的外部符号 __imp____stdio_common_vsprintf
1>..\..\bin\icuuc60.dll : fatal error LNK1120: 5 个无法解析的外部命令
1>已完成生成项目“common.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 1 个，跳过 0 个 ==========

**Comment by mingkuang-Chuyu** [comment]
这个应该是你自己的问题，因为VC-LTL从头到尾就没有 std_type_info.obj。
std_type_info.obj 相关代码都是从msvcrt.dll导入的。

所以初步断定VC-LTL没有正常引入至你的工程。


至于不使用中文，这个目前本地版本已经修正完毕，下个版本发布后就不会存在这样的情况了。

**Comment by mingkuang-Chuyu** [comment]
如果VC-LTL正常引用，在编译时会有一段提示：
info: 进入ltl普通模式，已准备对" "ltl" __ltlversion __ltlversionxp ".lib" "的引用。定义 __NO_LTL_LIB  可切换到超越模式。

如果你看不到提示那就说明 你没有引用

**Comment by sonyps5201314** [comment]
我后面看到“ 进入ltl普通模式"的 提示了 可是不引用std_type_info.obj会提示缺符号啊，要不你尝试用这个vc运行时编译icu试试嘛，____stdio_common_vsprintf是没有了，但是前面的错误问题依旧。
http://source.icu-project.org/repos/icu/trunk

**Comment by mingkuang-Chuyu** [comment]
能说明下具体什么工程吗？里面有很多工具

**Comment by mingkuang-Chuyu** [comment]
要不你给个包 直接回复在这里。我编译下 不就可以了……

Git可以拖拽，吧你的文件打包为zip 扔进来就可以了

**Comment by sonyps5201314** [comment]
icu是跨平台实现的Unicode库，当然也支持windows
http://download.icu-project.org/files/icu4c/59.1/icu4c-59_1-src.zip这里有直接的zip包下载
编译里面的icu4c\source\allinone\allinone.sln的common工程就重现问题了。

**Comment by mingkuang-Chuyu** [comment]
对  你这样回复不就可以了，告诉我 打开什么工程，编译什么项目……不然里面一大坨玩意谁知道你到底在说哪一个。反馈问题 也要说明重现过程不是吗？

**Comment by mingkuang-Chuyu** [comment]
此问题已经解决，请查收。
