### ISSUE TITLE
icu的common工程是编译通过了，但是其他工程还是不行

### ISSUE THREAD

**Issue by sonyps5201314** [Chuyu-Team/VC-LTL#13]
辛苦了，common是编译通过了，但是其他工程好像还是不行。
另外推荐一种配置方式：
1.环境变量中添加VC-LTL：你的VC-LTL的git版本存放路径
2.工程INCLUDE路径中添加: $(VC-LTL)\VC\$(PlatformToolsetVersion)\include;$(VC-LTL)\VC\$(PlatformToolsetVersion)\atlmfc\include;$(VC-LTL)\ucrt\$(TargetUniversalCRTVersion);
3.工程LIB路径中添加: :$(VC-LTL)\$(PlatformShortName);$(VC-LTL)\VC\$(PlatformToolsetVersion)\lib\$(PlatformShortName);$(VC-LTL)\ucrt\$(TargetUniversalCRTVersion)\lib\$(PlatformShortName);
应该能编译出来整个icu的解决方案工程并可正常运行时，VC-LTL就趋于完美可实用阶段了。

1>------ 已启动生成: 项目: i18n, 配置: Release Win32 ------
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1189,5): warning MSB8012: TargetPath(N:\Open_Code\icu\icu4c\source\i18n\.\..\..\lib\i18n.dll) does not match the Linker's OutputFile property value (N:\Open_Code\icu\icu4c\bin\icuin60.dll). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1191,5): warning MSB8012: TargetName(i18n) does not match the Linker's OutputFile property value (icuin60). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
1>  正在创建库 ..\..\lib\icuin.lib 和对象 ..\..\lib\icuin.exp
1>ltl.lib(_msvcrt.obj) : warning LNK4217: 本地定义的符号 __invoke_watson 在函数 __invalid_parameter_noinfo_noreturn 中导入
1>digitlst.obj : error LNK2019: 无法解析的外部符号 __imp___create_locale，该符号在函数 "public: static double __cdecl icu_60::DigitList::decimalStrToDouble(char *,char * *)" (?decimalStrToDouble@DigitList@icu_60@@SANPADPAPAD@Z) 中被引用
1>digitlst.obj : error LNK2019: 无法解析的外部符号 __imp___free_locale，该符号在函数 _digitList_cleanup 中被引用

**Comment by mingkuang-Chuyu** [comment]
我说 大爷，你反馈的也太杂乱无章了吧……我还看到了2个工程配置错误。就不能简单的做个总结……你做下总结不就减轻了我的工作量？

目前编译不通过的有:
i18n
io
iotest
toolutil
其他都能编译通过，此外i18n是使用了二个不支持的C函数，这个应该很快会修正。另外三个都是使用C++里面的输入输出流。这个短时间里面都是无法支持的。另外也可以考虑调整下源代码，毕竟兼容性这种事情是双方的事情。尽量使用简单C函数实现。比如i18n比较函数使用的就不合理……

**Comment by sonyps5201314** [comment]
我以为给你看结果你会觉得更直观呢😂

**Comment by mingkuang-Chuyu** [comment]
Hi，问题已经基本修正。目前可以说99%兼容。

还有一个 i18n 工程编译不通过，但是可以定义 `U_USE_STRTOD_L = 0` 解决临时解决。

完全兼容还需要一点时间。

**Comment by mingkuang-Chuyu** [comment]
已经修正，添加 _create_local以及_free_locale支持。请使用最新LTL，然后继续。谢谢
