### ISSUE TITLE
知名开源项目PPSSPP 中libkirk无法编译通过.

### ISSUE THREAD

**Issue by peaceshi** [Chuyu-Team/VC-LTL#15]
都是找不到XXXX,估计是没有支持,希望能够加入支持.

具体问题比较多,请编译PPSSPP,一目了然.
PPSSPP官方项目地址:
https://github.com/hrydgard/ppsspp

如何编译(官方Wiki):
https://github.com/hrydgard/ppsspp/wiki/Build-instructions

PS:它的默认是7.0的sdk而且无法切换到win10.我并没有编译其中支持UWP的版本,只是普通win32 X64 Release.

谢谢.

**Comment by mingkuang-Chuyu** [comment]
Hi，可以正常编译。只是这个工程本身没有按规范编写，Release工程没有定义 NDEBUG 宏。
导致 VC-LTL 以为不是Release。我可以在属性表中，强制添加一个 NDEBUG 宏，但是建议你还是反馈到PPSSPP。让他们工程更加规范一些。谢谢

**Comment by mingkuang-Chuyu** [comment]
出此之外，反馈 建议你  贴几个 象征性的错误信息。这样也方便我快速定位问题。 如果你当时贴了 几个编译不通过的信息，那么我可以更快的告诉你原因，都不必下载源代码。
谢谢

**Comment by mingkuang-Chuyu** [comment]
我还是不加了，加了其他项目就出现  NDEBUG重定义警告。另外我也看了PPSSPP其他项目的Release都有NDEBUG宏，就这个没有。八成是被作者误删了。你给PPSSPP 反馈BUG吧，然后暂时本地先给libkirk的配置添加一个NDEBUG宏

**Comment by mingkuang-Chuyu** [comment]
1ace4178 规避了这个问题，现在调整为 !_DEBUG 宏检测
