### ISSUE TITLE
编译PPSSPP出现问题.

### ISSUE THREAD

**Issue by peaceshi** [Chuyu-Team/VC-LTL#16]
LNK2005	"protected: __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::basic_streambuf<char,struct std::char_traits<char> >(void)" (??0?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAA@XZ) 已经在 native.lib(stringutil.obj) 中定义

LNK2001	无法解析的外部符号 __imp___stdio_common_vsprintf

LNK2001	无法解析的外部符号 __imp___stdio_common_vfprintf

LNK2001	无法解析的外部符号 __std_exception_copy

已经提交了NDEBUG的问题.使用了最新的VC-LTL.

**Comment by mingkuang-Chuyu** [comment]
能具体说说是哪个项目吗？我本地编译所有项目都是通过的

**Comment by mingkuang-Chuyu** [comment]
比如，打开那个sln，然后编译哪个项目。我我猜测VC LTL并没有被引用到项目中。

**Comment by peaceshi** [comment]
@mingkuang-Chuyu PPSSPPHeaderless.凡是它引用的都出现问题

**Comment by mingkuang-Chuyu** [comment]
嗯，现在我在家，家里的网比较，慢，下载需要点时间。等会给你答复。谢谢，期间你也看看。如果vc ltl被引用，编译会有vc ltl正在使用的提示。

**Comment by mingkuang-Chuyu** [comment]
什么梗，Release /MD编译，就算不用LTL，编译器会崩溃，，，说什么尝试简化x处代码。估计触发什么编译器内部BUG了。编译器是VS 2017 15.3.1，明天我升级到最新2017再说吧。

**Comment by mingkuang-Chuyu** [comment]
一共有二个问题，
一个是ppsspp本身问题，它只支持MT编译。因为ffmeg\Windows\下面几个lib都是mt编译的。所以，如果需要支持，那么必须使用VC-LTL编译出ffmeg。

还有一个问题是VC-LTL暂时不支持C++ 11新增的跨线程异常传递。

这个问题是已知问题，我也在完善中。另外ppsspp这个项目配置真的是乱的没法说，很多配置都是直接写死的。我建议你反馈下，可以继承父属性，，这样有助于提高通用性。


最后，当VC-LTL完成跨线程异常传递时，我会关闭此问题。因为我们不负责提供ffmeg库。

谢谢

**Comment by mingkuang-Chuyu** [comment]
还有一点，这个工程使用2017 Release编译就直接报错，2015才行。这虽然是微软BUG但是也希望能确认下这个问题，是否具有普遍性。

**Comment by peaceshi** [comment]
@mingkuang-Chuyu 我也发现了这个乱的不行的配置，修改了一些选项并且提交了pr，直接被否了，那老哥直接告诉我因为一些原因for some reason不要去动编译选项（可能是玄学问题）。我在本地vs2017能正常编译，用的最新版。但是这几天wi”n版本在CI上的编译突然无法通过，我....emmm。我也会持续尝试解决办法，试一试继承父属性能否通过pr，十分感谢。

**Comment by mingkuang-Chuyu** [comment]
谢谢反馈，已经添加夸线程异常传递支持。如果有其他问题，可以重新打开此问题，然后在这里回复即可。
