### ISSUE TITLE
visual studio 2015+QT5.8 Release链接出错

### ISSUE THREAD

**Issue by csuft** [Chuyu-Team/VC-LTL#19]
项目是在Visual Studio 2015下基于Qt5.8开发，Release版本编译报如下链接错误：
![2018-02-01_145236](https://user-images.githubusercontent.com/3948137/35665120-ad9f973e-075f-11e8-9dbc-d2b99a8e82e8.png)
Windows SDK版本为10.0.16299.0，Visual Studio版本为：
![2018-02-01_145445](https://user-images.githubusercontent.com/3948137/35665176-e05c51c6-075f-11e8-8f34-939129594100.png)

**Comment by mingkuang-Chuyu** [comment]
这些符号都是有的。话说你是按帮助做的吗？

**Comment by csuft** [comment]
![2018-02-02_100618](https://user-images.githubusercontent.com/3948137/35713156-c4bd7f66-0800-11e8-8205-1d05fffa71eb.png)
我的确是有复制到工程下面，然后添加到工程的。尽管我是通过cmake添加的，但是这也不影响吧。

**Comment by mingkuang-Chuyu** [comment]
已经解决，自身工程配置问题
