### ISSUE TITLE
装了Visual Studio 2015 Update3 KB3165756后还是提示warning

### ISSUE THREAD

**Issue by waiting4love** [Chuyu-Team/VC-LTL#20]
环境：Win10 Pro x64 + VS2015 
我已经安装了KB3165756，在About里能看到版本号是14.0.25431.01 Update 3。
我看了一下ltlvcrt.props代码，里面确定版本的方法是查找{4B1849F2-3D49-325F-B997-4AD0BF5B8A09}这一条记录，但是我在注册表里没有这一条。

**Comment by waiting4love** [comment]
补充：
在这个注册项里：
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{89ed6293-813d-4d4e-9004-4233efc2bae7}
![snipaste_2018-02-10_12-12-52](https://user-images.githubusercontent.com/36320323/36058474-d3d63e82-0e5b-11e8-8efb-31be53f24f5c.png)

**Comment by mingkuang-Chuyu** [comment]
已经解决，原来VS 2015 Update3本身版本号就是24210，但是VS 2017 for VC 2015 Update3平台工具集版本号是 24225
