### ISSUE TITLE
编译WTL程序链接时会提示没有std::nothrow

### ISSUE THREAD

**Issue by waiting4love** [Chuyu-Team/VC-LTL#21]
无法解析的外部符号 "struct std::nothrow_t const std::nothrow" (?nothrow@std@@3Unothrow_t@1@B)，该符号在函数 "public: int __thiscall ATL::CExpansionVector::Add(wchar_t const *,wchar_t const *)" (?Add@CExpansionVector@ATL@@QAEHPB_W0@Z) 中被引用

分析：
statreg.h文件中CExpansionVector::Add用到了_ATL_NEW
_ATL_NEW的定义在atldef.h中，#define _ATL_NEW new(std::nothrow)

解决：
方案一、在自己的程序里定义一个全局变量 struct std::nothrow_t const std::nothrow;
方案二、预定义_ATL_DISABLE_NOTHROW_NEW

**Comment by mingkuang-Chuyu** [comment]
自身问题，这个符号在 ltlcprt.lib/ltlcprtxp.lib里存在的好好的……
看看自身工程设置是不是把`附加依赖项`的引用链破坏了，具体参考reame的4.2 小结

**Comment by waiting4love** [comment]
我新建一个WTL工程，默认配置+LTL也会报这个错误。可能是我的VS2015安装问题？等我下个2017试试

**Comment by mingkuang-Chuyu** [comment]
建议你提供工程吧，不然实在是不好跟踪。

**Comment by waiting4love** [comment]
能不能给我发个邮件，我的邮箱是yongjun.mao(AT)outlook.com，我把工程发给你

**Comment by mingkuang-Chuyu** [comment]
HI，已经发送了邮件，mingkuang#live.com请查收

**Comment by mingkuang-Chuyu** [comment]
Hi，请抽空提供工程，如果长时间未能提供工程，最终我只能当作无效反馈处理。

毕竟我们也使用WTL项目，并未能发现此问题，std::nothrow;能够正常使用。

**Comment by mingkuang-Chuyu** [comment]
已经确认，原来msvcrt.lib也有一个弱符号的const nothrow_t nothrow；

如果需要临时解决，可以
#include <use_ansi.h>

下个版本中，一起解决此问题

**Comment by mingkuang-Chuyu** [comment]
已经修复，同步到最新版即可。
