### ISSUE TITLE
VS2017 O2编译代码运行出现异常

### ISSUE THREAD

**Issue by mingkuang-Chuyu** [Chuyu-Team/VC-LTL#23]
反馈者：风清凉
影响平台：VS2017 + O2编译（Od以及O1均正常，另外不用VC-LTL也正常）

严重等级：严重

表现：Duilib弹出模态窗口一定几率导致父创建界面不刷新。

临时解决方案：暂时不用VC-LTL或者用O1或者降级到2015。

这可能是VS2017 代码优化器存在BUG，遇到特殊代码导致编译的二进制代码有误。

此问题需要继续跟踪。

**Comment by augustheart** [comment]
一定几率这个就愁人了，我个人粗浅的经验倒是觉得这种一定几率的问题机器码层次的问题不大。有样例么。

**Comment by mingkuang-Chuyu** [comment]
没……对方已经降级到VS2015了，2017 + O2在他那里几乎必现。

**Comment by mingkuang-Chuyu** [comment]
暂时关了吧，暂时没有发现其他有关的信息。而且问题也不在出现了。
