### ISSUE TITLE
能不能顺便修改一下xp下面_stat\_stat64这一批函数无法正常工作的bug？

### ISSUE THREAD

**Issue by augustheart** [Chuyu-Team/VC-LTL#24]
目前已知至少从2015开始的这批函数在xp模式下面编译的代码在xp下是不能正常运行的，返回值是-1。我是在编译flac的时候发现这个问题的，在反复检查后最终发现是微软的库的实现问题，从网上查到的信息，这个问题三年前就有人提出来了，甚至vs项目组也知道，还有微软员工声称已经已经修复了，但是实际上到今天为止仍然没有修正，看来这辈子是不用指望微软了。
这个并不是VC-LTL的bug，不过我想来想去，把修正放在LTL这个里面再合适不过了。如果在其它库中修正，每个项目都要从底层修改，非常麻烦兼丑陋。

**Comment by mingkuang-Chuyu** [comment]
Hi，如果确实是VC本身BUG。我也可以修复。但是建议你提供下代码。方便我进行全平台覆盖……

**Comment by augustheart** [comment]
需要测试代码呢？还是修正代码？规则不是很懂……

**Comment by mingkuang-Chuyu** [comment]
当然是 BUG重现代码……你不贴代码我怎么测试这个问题是否修复？另外我刚才测试了下，XP此函数能正常使用，无论是绝对路径还是相对路径还是'\\'结束的路径都正常。

**Comment by mingkuang-Chuyu** [comment]
所以我很不解你说有问题，然而我测试结果却都正常。因此既然你说有问题，那么请你贴上能重现此问题的代码。另外还请说明具体环境信息。
比如：对于需要外部参数传入的，请明确说明应该传入什么样子的参数。在什么操作系统（WinXP RTM还是所有XP均可）？

而你什么也不说如何触发不正常，我也不知道从何处下手。

**Comment by augustheart** [comment]
抱歉，这个问题原来LTL已经修正过了……在vs的自带的crt下面才能重现这个问题，我之前测试的时候一直是用debug版，一直没意识到debug版下面是没启用LTL编译的。

**Comment by mingkuang-Chuyu** [comment]
嗯，最后能解决问题就好。
