### ISSUE TITLE
非中文环境可能出现C4566警告

### ISSUE THREAD

**Issue by mingkuang-Chuyu** [Chuyu-Team/VC-LTL#27]
反馈者：@myfreeer
影响：低

相关信息：
https://github.com/Chuyu-Team/VC-LTL/blob/39d232b5f932614c837a62ec5e8fb6689e0a4e97/ucrt/10.0.10240.0/stdlib.h#L60

```
warning C4566: character represented by universal-character-name '\u529F' cannot be represented in the current code page (1252)
```

**Comment by myfreeer** [comment]
```cxx
#pragma warning(push)
#pragma warning(disable: 4566)
// Your function
#pragma warning(pop)
```

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL/blob/9f6f6ee0f06ee5c49858e83bbc6a74618dd32f36/ucrt/10.0.10240.0/stdlib.h#L60

https://github.com/Chuyu-Team/VC-LTL/blob/9f6f6ee0f06ee5c49858e83bbc6a74618dd32f36/ucrt/10.0.15063.0/stdlib.h#L62

https://github.com/Chuyu-Team/VC-LTL/blob/9f6f6ee0f06ee5c49858e83bbc6a74618dd32f36/ucrt/10.0.16299.0/stdlib.h#L62
