### ISSUE TITLE
找不到msvcrt_Platform.lib

### ISSUE THREAD

**Issue by augustheart** [Chuyu-Team/VC-LTL#31]
我应该没看错……VC-LTL\config中的config.props里面
<AdditionalDependencies Condition=" '$(SupportLTL)'=='true'">msvcrt_Platform.lib;ltl.lib;vc.lib;ucrt.lib;%(AdditionalDependencies)</AdditionalDependencies>
msvcrt_Platform.lib这个文件是不存在的。

**Comment by augustheart** [comment]
另外确认一件事，当前的版本是否即使加载VC-LTL helper for Visual Studio.props也会提示严
“警告	LTL2100	此文件已经弃用，未来版本随时可能删除。强烈建议直接使用“VC-LTL helper for Visual Studio.props”！！！！”？

**Comment by mingkuang-Chuyu** [comment]
Hi, 感谢你的支持。

## msvcrt_Platform.lib这个文件是不存在
这是因为VC-LTL分发方式已经更改，源代码中已经不再提供lib文件，因为lib文件太大了，已经导致仓库体积剧增。
请下载[VC-LTL Binary](https://github.com/Chuyu-Team/VC-LTL/releases/tag/3.0.0.2)然后解压使用。


## VC-LTL helper for Visual Studio.props
项目中对Shared.props、ltlvcrt.props以及ltlvcrtWinXp.props的引用全部需要删除，不然就会持续发出这个警告。我可能会在半年后删除这些文件。
