### ISSUE TITLE
无法解析的外部符号 __imp___p__fmode

### ISSUE THREAD

**Issue by augustheart** [Chuyu-Team/VC-LTL#32]
在编译luajit的x64版本时候报错。
link /nologo /DLL /out:lua51.dll lj_*.obj lib_*.obj
  正在创建库 lua51.lib 和对象 lua51.exp
lj_clib.obj : error LNK2019: 无法解析的外部符号 __imp___p__fmode，该符号在函数 clib_getsym 中被引用

使用的是luajit2.0.5，已经在msvcbuild.bat文件中手动改为MD模式
@set LJCOMPILE=cl **/MD** /nologo /c /O2 /W3 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_STDIO_INLINE=__declspec(dllexport)__inline

**Comment by mingkuang-Chuyu** [comment]
确认问题，稍后会在这里提供临时解决版本。

**Comment by mingkuang-Chuyu** [comment]
### 临时解决方案
下载 temp.zip，然后替换 本地VC-LTL文件即可。
[temp.zip](https://github.com/Chuyu-Team/VC-LTL/files/2034682/temp.zip)


感谢你的支持

**Comment by mingkuang-Chuyu** [comment]
[3.0.0.3-alpha1](https://gitee.com/Chuyu-Team/VC-LTL/releases/3.0.0.3-alpha1)已经包含了对此问题的修复。

**Comment by augustheart** [comment]
这么快就修复了，感谢
