### ISSUE TITLE
不支持去掉msvcp140.dll的依赖吗？

### ISSUE THREAD

**Issue by yuyifu** [Chuyu-Team/VC-LTL#33]
如题？在使用中发现不再依赖msvcr140.dll，有支持msvcp140解依赖的打算吗？

**Comment by mingkuang-Chuyu** [comment]
不是已经完整支持STL了吗？

https://github.com/Chuyu-Team/VC-LTL#2-vc-ltl-compatibility

**Comment by mingkuang-Chuyu** [comment]
下次建议你自己先尝试下，如果发现问题 在提交issus不迟……
直接提问反而导致解决问题的周期变长
