### ISSUE TITLE
请求增加clang-LLVM工具集支持

### ISSUE THREAD

**Issue by hzqst** [Chuyu-Team/VC-LTL#34]
当前版本VC_LTL不支持LLVM工具集编译，我做了一些修改让VC-LTL强行支持：

1.\VCLTL\config\config.props

   \<!--计算机已经安装LLVM--\>
    \<VC-LTLUsedToolsVersion Condition=" ('$(VC-LTLUsedToolsVersion)'=='') And ('$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\LLVM\LLVM'!='') "\>14.0.24231\</VC-LTLUsedToolsVersion\>
    \<VC-LTLUsedToolsVersion Condition=" ('$(VC-LTLUsedToolsVersion)'=='') And ('$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\LLVM\LLVM'!='') "            \>14.0.24231\</VC-LTLUsedToolsVersion\>

\<SupportPlatformToolsetNormal Condition="('$(SupportPlatformToolsetNormal)'=='') And ('$(PlatformToolset)'=='v140')"\>true\</SupportPlatformToolsetNormal\>
    \<SupportPlatformToolsetNormal Condition="('$(SupportPlatformToolsetNormal)'=='') And ('$(PlatformToolset)'=='v141')"\>true\</SupportPlatformToolsetNorma\>

\<SupportPlatformToolsetNormal Condition="('$(SupportPlatformToolsetNormal)'=='') And ('$(PlatformToolset)'=='LLVM-vs2015_xp')"\>true\</SupportPlatformToolsetNormal\>
 \<SupportPlatformToolsetNormal Condition="('$(SupportPlatformToolsetNormal)'=='') And ('$(PlatformToolset)'=='LLVM-vs2017_xp')"\>true\</SupportPlatformToolsetNormal\>

\<SupportPlatformToolsetNormal Condition="('$(SupportPlatformToolsetNormal)'=='') And ('$(PlatformToolset)'=='LLVM-vs2015')"\>true\</SupportPlatformToolsetNormal\>
  \<SupportPlatformToolsetNormal Condition="('$(SupportPlatformToolsetNormal)'=='') And ('$(PlatformToolset)'=='LLVM-vs2017')"\>true\</SupportPlatformToolsetNormal\>

2.修改\VCLTL\_msvcrt.h为UTF-8编码

3.修改\VCLTL\ucrt\10.0.xxxxx.0\中头文件（如stdio.h）可能出现的unicode LTL提示文本，全部删除或修改为UTF8

**Comment by mingkuang-Chuyu** [comment]
谢谢支持，预览版已经支持
https://gitee.com/Chuyu-Team/VC-LTL/releases/3.0.0.4_Preview

**Comment by mingkuang-Chuyu** [comment]
同理 Clang with Microsoft CodeGen以及Clang 3.7 with Microsoft CodeGen也已经添加完成。
