### ISSUE TITLE
无法解析的外部符号 __imp___configthreadlocale

### ISSUE THREAD

**Issue by zhaooptimus** [Chuyu-Team/VC-LTL#36]
xp模式编译chromium时，出现无法解析的外部符号__imp___configthreadlocale

编译qt 5.6.3中qwebengine模块时，在链接时出现符号解析错误:
**skia_library.lib(skia_library.GrGLProgramBuilder.obj) : error LNK2019: 无法解析的外部符号 __imp___configthreadlocale，该符号在函数 "public: static class GrGLProgram * __cdecl GrGLProgramBuilder::CreateProgram(struct GrGpu::DrawArgs const &,class GrGLGpu *)" (?CreateProgram@GrGLProgramBuilder@@SAPAVGrGLProgram@@ABUDrawArgs@GrGpu@@PAVGrGLGpu@@@Z) 中被引用
..\..\lib\Qt5WebEngineCore.dll : fatal error LNK1120: 1 个无法解析的外部命令**

**环境信息：（Information）**
 - OS: win10 x64
 - VC-LTL  3.0.0.3
 - VC Tools Version 14.0.25431.01 Update 3
 - UCRT Version  14.0.24210
 - Platform  x86

**其他信息（Additional context）**
其他有关于这个问题的内容。

**Comment by mingkuang-Chuyu** [comment]
重复反馈，#17
Windows XP模式中暂不支持locale的一些相关特性。如有疑问，请在#17中回复。

**Comment by mingkuang-Chuyu** [comment]
建议你评估下支持XP是否必须。

在Windows XP中不支持threadlocale，_因此configthreadlocale实现代价很大。这也是为什么这个问题一直没修复。

如果你确实需要支持XP，那么建议你看看调用configthreadlocale的地方是不是关闭threadlocale ，如果是关闭，那么问题不大，自己写个空的configthreadlocale就可以了。

如有疑问可以在下方回复。
