### ISSUE TITLE
為什麼xp mode會有一堆全局變量

### ISSUE THREAD

**Issue by stevefan1999** [Chuyu-Team/VC-LTL#37]
就是mbctable, mbbtable, LcidToLocaleNameTable, LocaleNameToIndexTable這些沒有引用過用過的變量在浪費空間, 11K呀😥

**Comment by stevefan1999** [comment]
怎麼會沒有呢
但是相同配置下 我用非XP模式可順利消走這四個全局
errtable modulesName依然存在，懷疑是linker問題了

**Comment by mingkuang-Chuyu** [comment]
应该不是linker的事情，你应该是用了啥国际化特性，而XP不支持只能静态导入不支持的函数。而Vista以后的系统直接可以使用系统API。

**Comment by mingkuang-Chuyu** [comment]
要是XP模式不用特殊处理，那我特意准备个XP模式LTL库做什么？

**Comment by stevefan1999** [comment]
🤔有道理 但是ida完全查不到引用
但是我沒有用什麼i18n 純c的程序

**Comment by mingkuang-Chuyu** [comment]
我测试了下确实是这样的，没有任何引用也会导致LcidToLocaleNameTable、LocaleNameToIndexTable被引入……但是这个是微软Bug……我也无能为力，只能反馈微软解决。

**Comment by mingkuang-Chuyu** [comment]
我发现微软的UCRT没有这个问题……这个问题需要跟踪一下。

**Comment by mingkuang-Chuyu** [comment]
发现微软的也会这样，刚才看错 MD了，MT下 这些全局对象也会始终引入。因此这个问题是微软自身的问题。
