### ISSUE TITLE
在msvcrt.dll有些C运行时的函数声明可能和VC-LTL里面的函数声明不同

### ISSUE THREAD

**Issue by MouriNaruto** [Chuyu-Team/VC-LTL#4]
将近一年前，开发NCleaner的时候发现……有个按格式输出字符串函数由于调用不正确导致应用奔溃

后来换了另一个函数实现，就没再出问题

**Comment by mingkuang-Chuyu** [comment]
根据文档说明 https://msdn.microsoft.com/en-us/library/28d5ce15.aspx

已经修正 vswprintf/_swprintf/swprintf实现到最新UCRT版本

同步最新VC-LTL即可
