### ISSUE TITLE
XP编译问题

### ISSUE THREAD

**Issue by killvxk** [Chuyu-Team/VC-LTL#40]
1>libconcrt.lib(SchedulerProxy.obj) : error LNK2001: 无法解析的外部符号 __RTDynamicCast
1>msvcrt_Platform.lib(__RTDynamicCast.obj) : error LNK2001: 无法解析的外部符号 __RTDynamicCast
1>msvcrt_Platform.lib(__RTDynamicCast.obj) : error LNK2001: 无法解析的外部符号 RTDynamicCast_downlevel

**Comment by mingkuang-Chuyu** [comment]
确认，但是建议以后反馈问题按照模板来，因为反馈的信息不全。

比如这次，只有在x64 + XP才会编译不通过，而你的信息中从头到尾就没有提到。

**Comment by killvxk** [comment]
忘了，以为都原生X64...

**Comment by mingkuang-Chuyu** [comment]
感谢支持，https://github.com/Chuyu-Team/VC-LTL/releases/tag/4.0.0.11-Preview已经修复了此问题
