### ISSUE TITLE
无法解析的外部符号 __byteswap_ulong __byteswap_ushort __byteswap_uint64

### ISSUE THREAD

**Issue by wangwenx190** [Chuyu-Team/VC-LTL#41]
**描述**
前端 Clang 6.0.1，后端 VS2017 15.8.2，编译 Qt 5.11.1，出现以下错误：
sqlite3.obj : error LNK2001: 无法解析的外部符号 __byteswap_ulong
sqlite3.obj : error LNK2001: 无法解析的外部符号 __byteswap_ushort
sqlite3.obj : error LNK2001: 无法解析的外部符号 __byteswap_uint64

**环境信息**
 - OS: Win10 17134.254 x64
 - VC-LTL Version: 4.0.0.12-Preview
 - VC Tools Version: 14.15.26706
 - UCRT Version: 10.0.17134.12
 - Platform: x86

**Comment by wangwenx190** [comment]
在相同的环境和配置参数条件下，不用VC-LTL是可以完美编译的，使用VC-LTL之后就报错了，不过只有那一个小插件报错，其他组件都没有报错。

**Comment by mingkuang-Chuyu** [comment]
确认，在无法支持内部函数 或者 关闭 内部函数 的情况下 使用 此类函数会导致无法编译。
