### ISSUE TITLE
关于VC-LTL helper for nmake.cmd这个文件的换行问题，还是拿出来说说吧

### ISSUE THREAD

**Issue by augustheart** [Chuyu-Team/VC-LTL#43]
之前在某个issue中也提到过。之后发现这里也一直没修改过。后来有段时间不怎么写c++了，这个库也关注少了（js的时代嘛，一言难尽……）。在今天这个无心工作一心只想为祖国母亲庆生的时候，为了打发下班前的漫长时光，还是拿出来交流一下吧。
简单说就是VC-LTL helper for nmake.cmd（包括里面调用的config.cmd）这个文件里面的换行符是\n(0xa)，实际上windows的命令行只接受\r\n(0xd0xa)这种换行，如果只有\n的话，它会把下面一行的内容当做同一行的内容，然后各种奇怪的错误就出现了。所以在我本地，这个文件一直都是要手动重新处理过后才能正常用vs的“开发人员命令行”执行的。
这个问题其实应该很容易发现的，但是@mingkuang-Chuyu 一直没有提到，甚至也没有别人提到这个问题。这就很值得探讨了。可以基本上肯定，这个文件在@mingkuang-Chuyu 那里是正常执行的。那么，是不是我们的环境有什么不同呢？

（ps：虽然看我的执行路径是在msys下面，实际上只是因为我用msys做git客户端而已，并不是用msys执行的）
`E:\CodeProject\msys2\home\admin\VC-LTL>call "VC-LTL helper for nmake.cmd"
'2.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'7.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'会维持在VS2008。如果你需要高度兼容微软UCRT，那么请不要打开此选项！！！' 不是内部或外部命令，也不是
可运行的程序
或批处理文件。
'件根目录存在VC-LTL？' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'onfig' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
文件名、目录名或卷标语法不正确。
文件名、目录名或卷标语法不正确。
系统找不到指定的路径。`

**Comment by mingkuang-Chuyu** [comment]
我插了记录，你当时并没有反应这个问题，只是说缺少lib，还有一个属性表的警告问题。


你现在说的问题跟当时你反馈的问题其实是同一回事情。

请你手动下载Binary文件，binary文件是后缀是7z，名字里也写了Binary。不要去下载git提供的zip。变成\n不是我导致，而是git打包的zip的问题。你去下载git提供的源代码zip包，自然就会有问题。如果你真想反馈，建议你反馈给github。

如有疑问可以在此继续。
