### ISSUE TITLE
Single header?

### ISSUE THREAD

**Issue by optomux** [Chuyu-Team/VC-LTL#44]
Try provide single header.

**Comment by mingkuang-Chuyu** [comment]
what?

**Comment by MouriNaruto** [comment]
@mingkuang-Chuyu 如果我没理解错误的话，他的意思是提供单个头文件版本的VC-LTL。

**Comment by optomux** [comment]
Yes! Would be very nice. Something like SQlite.

**Comment by mingkuang-Chuyu** [comment]
抱歉，提供单文件版VC-LTL会限制VC-LTL的使用。曾经VC-LTL就是单文件版的，功能非常简陋，但是使用非常复杂，很多人都不会配置。而现在VC-LTL虽然由很多文件组成，但是一个属性表就能搞定，基本都是透明的。

所以 从 使用的便捷性，VC-LTL的函数覆盖率出发考虑，暂时不会考虑单文件版本。我希望提供一个使用简单、优雅的库，并不追求那个所谓的什么单文件。
