### ISSUE TITLE
VC-LTL编译ICU6.31报错-main函数argv参数默认被展开问题

### ISSUE THREAD

**Issue by xspeed1989** [Chuyu-Team/VC-LTL#45]
VS2017
ICU 6.31
VC-LTL-4.0.0.26-Binary-VS2017.7z
make 阶段

Unpacking ./in/icudt63l.dat and generating out/tmp/icudata.lst (list of data files)
PATH=../lib:../stubdata:../tools/ctestfw:$PATH  ../bin/icupkg -d ./out/build/icudt63l --list -x \* ./in/icudt63l.dat -o out/tmp/icudata.lst
usage: icupkg.exe [-h|-?|--help ] [-tl|-tb|-te] [-c] [-C comment]
        [-a list] [-r list] [-x list] [-l [-o outputListFileName]]
        [-s path] [-d path] [-w] [-m mode]
        [--auto_toc_prefix] [--auto_toc_prefix_with_type] [--toc_prefix]
        infilename [outfilename]
make[1]: *** [Makefile:493: out/tmp/icudata.lst] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/John/Desktop/icu/source/data'
make: *** [Makefile:153: all-recursive] Error 2

如果不加载VC-LTL nmake helper则不会出现此问题

**Comment by mingkuang-Chuyu** [comment]
_configure_narrow_argv_downlevel、_configure_wide_argv_downlevel中有和逻辑写错了。

'_get_startup_argv_mode() == _crt_argv_mode::_crt_argv_unexpanded_arguments'
写成了
'_get_startup_argv_mode() != _crt_argv_mode::_crt_argv_unexpanded_arguments'

导致默认情况下参数被展开，从而导致了此问题。

感谢反馈，将在4.0.0.27中修复，大概今天下午会发布新版本。

**Comment by xspeed1989** [comment]
感谢！

**Comment by krhomme** [comment]
我也遇到这个问题，请问你是怎么解决的？

**Comment by xspeed1989** [comment]
更新VC-LTL版本到最新即可

fujie <notifications@github.com> 于2019年4月30日周二 上午10:45写道：
