### ISSUE TITLE
使用fastcall调用约定编译时，有些crt函数导致崩溃

### ISSUE THREAD

**Issue by imReker** [Chuyu-Team/VC-LTL#46]
例如wcslen会跑飞。cdecl和stdcall没问题

  VC Tools Version : 14.15.26726
  UCRT Version     : 10.0.10240.0
  Platform         : x86

**Comment by mingkuang-Chuyu** [comment]
未能发现此问题。
wcslen正常工作，调用约定 __fastcall(/Gr)
14.16.27023，x86平台。
其实我觉得吧，建议你不用VC-LTL试试，可能某个函数你没有显示指定调用约定，导致崩溃了。
比如 main这种必须 __cdecl
DllMain、wWinMain这种必须 __stdcall

测试代码如下：
```cpp
int __cdecl main()
{
	auto cch = wcslen(L"123456789");

       //正常返回 9   __fastcall(/Gr)
	return cch;
}
```


如果你不用VC-LTL正常，要不就麻烦你提供个 测试工程吧。

**Comment by imReker** [comment]
抱歉，是我自己的问题，耽误你时间了

**Comment by mingkuang-Chuyu** [comment]
不客气，能找到问题就好。
