### ISSUE TITLE
请求添加VS2019支持

### ISSUE THREAD

**Issue by peaceshi** [Chuyu-Team/VC-LTL#47]
请求添加VS2019支持

Unknown MSVC_VERSION=1920

VS2019 Perview 2 增强了Cmake的支持.

测试Cmake项目时发现还未支持此版本visual studio.

**Comment by mingkuang-Chuyu** [comment]
还请耐心等待，等VS2019正式发布时，会支持的。预览版不想支持。

**Comment by shuax** [comment]
Visual Studio 2019 正式发布

https://visualstudio.microsoft.com/downloads/

**Comment by MouriNaruto** [comment]
坐等VS2019支持

**Comment by stevefan1999-personal** [comment]
前排支持

**Comment by mingkuang-Chuyu** [comment]
感谢大家的支持，4.0.1.3 Beta已经支持2019，
另外再送上平滑迁移方案，仅供参考。
https://zhuanlan.zhihu.com/p/61518123
