### ISSUE TITLE
仍然会提示计算机缺失MSVCRXXX.dll

### ISSUE THREAD

**Issue by awsl1** [Chuyu-Team/VC-LTL#48]
**bug标题（Describe the bug）**
使用VC-LTL后仍会提示丢失MSVCRXXX.dll

**如何重现此问题？（To Reproduce）**
按教程使用V141工具集编译程序并运行，启用强制XP兼容模式
程序：https://github.com/nagist/metahook

**预期行为（Expected behavior）**
正常情况应该是怎么样的？
正常启动HL

**相关截图（Screenshots）**
相关错误截图，截图最好大一点。
提示计算机丢失MSVCR120.dll MSVCR100.dll

**环境信息：（Information）**
 - OS: Windows 7 SP1 x64
 - VC-LTL Version 4.0.1.2 Beta
 - VC Tools Version [e.g. 14.0.24231, 14.14.26428]
 - UCRT Version  [e.g. 10240, 16299]
 - Platform  x86

**其他信息（Additional context）**
其他有关于这个问题的内容。
使用v141工具集编译，并启用强制XP兼容模式

**Comment by stevefan1999-personal** [comment]
檢查一下有什麼DLL引用
`dumpbin /imports <DLL>`

**Comment by awsl1** [comment]
@stevefan1999-personal
发现问题了 是外部dll的锅
另外还有一个问题 启用xp兼容模式仍然不能在xp运行 v141

**Comment by mingkuang-Chuyu** [comment]
@awsl1 
启用xp兼容任然无法再xp运行，能提供详细错误吗？要不你直接加群吧？这样方便及时沟通，如何？
qq群号在readme里面有。
谢谢

**Comment by augustheart** [comment]
外部dll一样可能导致xp模式下面不能运行。
所有相关的静态动态库可能都需要使用xp toolset编译。

**Comment by mingkuang-Chuyu** [comment]
没有其他人反馈相似的问题，并且长期没有回复，并且也不加群。暂时关闭此问题。
