### ISSUE TITLE
141 版本是否已经没有afxres.h了 ,我新建了一个141的RC文件貌似改成了winres.h ?

### ISSUE THREAD

**Issue by sgf** [Chuyu-Team/VC-LTL#5]
但VC-LTL中没有 winres.h
期待补充进来
或许只要在VC\141\atlmfc\include 直接复制一下winres.h 或者 afxres.h 进来？

当然 我是菜鸟 如果有错望指点

**Comment by sgf** [comment]
解决直接复制 afxres.h 进来就行了....

**Comment by mingkuang-Chuyu** [comment]
谢谢支持 VC 141一开始没有 这个文件，但是微软在VS 2017 15.2重新加入了这个文件，我也是才发现的。谢谢反馈

**Comment by mingkuang-Chuyu** [comment]
感谢 已经添加了 VC 15.2新增的 afx相关代码，感谢支持

**Comment by sgf** [comment]
XP 真的 可以放弃了。。。。
