### ISSUE TITLE
不知道能不能加一个vs版本检测提示

### ISSUE THREAD

**Issue by shuax** [Chuyu-Team/VC-LTL#50]
由于自己粗心大意，用的vs2019，下成了2017版本，一直报错研究了半天。如果有一个直接提示就更好了。

因为之前附件都是按照顺序排列。
![image](https://user-images.githubusercontent.com/6940583/56464424-c09e3880-641b-11e9-8f36-1234cd245fcb.png)

然后这次顺序换了一下，就下错了。
![image](https://user-images.githubusercontent.com/6940583/56464425-ceec5480-641b-11e9-89bb-6738d9f5815e.png)

**Comment by mingkuang-Chuyu** [comment]
谢谢反馈，其实这个是一个Bug。我添加了这个功能，但是因为Bug，导致没有生效。

**Comment by mingkuang-Chuyu** [comment]
[VC-LTL 4.0.1.7](https://github.com/Chuyu-Team/VC-LTL/releases/tag/4.0.1.7)
已经修复了此问题。
