### ISSUE TITLE
[LibMaker] not found

### ISSUE THREAD

**Issue by Voskrese** [Chuyu-Team/VC-LTL#51]
https://github.com/Chuyu-Team/VC-LTL/search?q=LibMaker&unscoped_q=LibMaker

`"D:\用户数据\Documents\Visual Studio 2017\Projects\ltlbuild\Debug\LibMaker.exe"`

**Comment by mingkuang-Chuyu** [comment]
Maybe share this tool in the future.

**Comment by mingkuang-Chuyu** [comment]
We'll provide LibMaker through the QQ group in the future, and we can go to the QQ group to download the latest version.
