### ISSUE TITLE
libvcruntime.lib(ehstate.obj) : error LNK2001: 无法解析的外部符号

### ISSUE THREAD

**Issue by shuax** [Chuyu-Team/VC-LTL#52]
**bug标题（Describe the bug）**
使用4.0.1.9版本后，64位编译出错，32位没问题

**相关截图（Screenshots）**
1>libvcruntime.lib(ehstate.obj) : error LNK2001: 无法解析的外部符号 "public: static unsigned __int64 * __cdecl __FrameHandler3::GetEstablisherFrame(unsigned __int64 *,struct _xDISPATCHER_CONTEXT *,struct _s_FuncInfo const *,unsigned __int64 *)" (?GetEstablisherFrame@__FrameHandler3@@SAPEA_KPEA_KPEAU_xDISPATCHER_CONTEXT@@PEBU_s_FuncInfo@@0@Z)

**环境信息：（Information）**
1>  VC-LTL Path      : VC-LTL-4.0.1.9-Preview-Binary-VS2019\
1>  VC Tools Version : 14.21.27702
1>  UCRT Version     : 10.0.17763.0
1>  Platform         : x64
1>  Using VC-LTL Vista Advanced Mode

**其他信息（Additional context）**
更新4.0.1.9后出现

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL/releases/tag/4.0.1.10
4.0.1.10 Beta已经修复。
感谢反馈
