### ISSUE TITLE
wmemchr 末识别符号

### ISSUE THREAD

**Issue by hotxp** [Chuyu-Team/VC-LTL#53]
VC-LTL Path      : E:\VC-LTL-VS2017\
VC Tools Version : 14.16.27023
UCRT Version     : 10.0.17763.0
Platform         : x86
Using VC-LTL Vista Advanced Mode
不引用 VC-LTL 库正常编译
引用后 提示 _wmemchr 符号末识别
重写 wmemchr 添加后正常编译
跟进源码是 std::string find 异常  单独测试 wmemchr string的 find 无法重现上面的问题！
重写函数可以得到解决！能找到原因修正它是最好不过！

**Comment by mingkuang-Chuyu** [comment]
感谢你的支持，，，，我会跟踪此问题。

**Comment by mingkuang-Chuyu** [comment]
我看了下 wmemchr  是wchar.h的 inline 函数啊。建议还是详细下错误日志，方便提供源代码的话直接发我下源代码。不方便的话那就QQ远程下。我们的QQ群是 633710173。

**Comment by hotxp** [comment]
这个我也觉得有点不可思议，事实上我就是在CRT里复制了一份 wmemchr 代码并引用它，问题得到解决
事实上还有一个问题没说，我感觉应该和这个是同样问题引起的。
malloc  calloc 之类 inline 个人猜测在某些情景下都存在类似的的问题
inline 对于编译器来说只是一个建议，编译器可能会忽略这个建议。

**Comment by mingkuang-Chuyu** [comment]
那个inline是微软原版编译器就如此，，，另外我本地无法复现，甚至故意自己声明个extern，再调用都不行。你本地复制一份就解决了，那你本地include <wchar.h>能解决吗？建议你加群我们群里说吧。

**Comment by mingkuang-Chuyu** [comment]
请问是否使用了LLVM？

**Comment by hotxp** [comment]
是，添加头文件的方法尝试过，无效。

**Comment by mingkuang-Chuyu** [comment]
这个问题另一个人反馈了，在LLVM里它自己搞了这个头文件，然后不是inline，单纯只是一个extern的，具体实现在一个obj里，但是不知道怎么回事，那个obj没有被链进来。具体还在跟踪。反正跟LLVM或者说libC++有些关系。

**Comment by mingkuang-Chuyu** [comment]
问题已经确认，是LLVM自身的问题。MD下就能表现出来，MT下由于微软的STL库刚好关闭了引用消除，然后就这样在STL的xwstoxfl.c 意外的导出了这个inline函数。所以MT下没有表现出来。而MD就没导出了，所以MD下LLVM自己就编译不过了，哪怕使用微软的。

下个版本我会将STL的静态库关闭引用消除，来规避此问题，关于最终解决方案 建议你反馈到LLVM。

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL/releases/tag/4.0.2.2-Beta
已经解决此问题，感谢反馈。
