### ISSUE TITLE
4.0.2.14-VS2017 CMake 编译 OpenCV，失败

### ISSUE THREAD

**Issue by dbyoung720** [Chuyu-Team/VC-LTL#59]
**bug标题（Describe the bug）**
4.0.2.14-VS2017 CMake 编译 OpenCV(X86)，失败，
提示没有定义：CMAKE_BUILD_TYPE，CMAKE_SYSTEM_NAME
添加了定义
  -DCMAKE_BUILD_TYPE=Release ^
  -DCMAKE_SYSTEM_NAME=Windows ^
CMake 才可以 config 通过，但 VS2017 编译无法通过，提示 16367 个错误。
(用的是 MT 方式编译)
WIN10X64+VS2017

**Comment by dbyoung720** [comment]
没人维护了？

**Comment by MouriNaruto** [comment]
请 加 群

**Comment by mingkuang-Chuyu** [comment]
建议加群吧，群号在readme有。应该是时机问题。

**Comment by mingkuang-Chuyu** [comment]
VC-LTL的属性表需要在工具集配置的后面。

**Comment by mingkuang-Chuyu** [comment]
长时间无反应同时其他人并未发现问题， 关闭此问题。

**Comment by zihanhuang** [comment]
遇到同样问题了。。应该加在cmakelist的什么位置？我加在
# ========================== GUI ==========================
status("")
status("  GUI: ")

这一段上面，没有报错，但是和我的项目link时报错。运行时不一致，opencv还是用的普通的mt

**Comment by mingkuang-Chuyu** [comment]
具体什么位置我也不知道，但是看错误提示 我知道 位置错了。VC-LTL的属性表需要在 changetool 以后才能引入，如果在这之前引入那么就会因为各种前置环境变量没有加载而各种报错。
