### ISSUE TITLE
好像少了一些符号？

### ISSUE THREAD

**Issue by hzqst** [Chuyu-Team/VC-LTL#6]
IDA看了下都是msvcp140的东西
是不是msvcp140没做兼容。。。

1>wsclient.obj : error LNK2001: 无法解析的外部符号 __imp___Query_perf_frequency
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __thiscall std::_Lockit::~_Lockit(void)" (__imp_??1_Lockit@std@@QAE@XZ)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __thiscall std::_Lockit::_Lockit(int)" (__imp_??0_Lockit@std@@QAE@H@Z)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) class std::basic_ostream<char,struct std::char_traits<char> > std::cout" (__imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) private: static class std::locale::_Locimp * __cdecl std::locale::_Getgloballocale(void)" (__imp_?_Getgloballocale@locale@std@@CAPAV_Locimp@12@XZ)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) private: static class std::locale::_Locimp * __cdecl std::locale::_Init(bool)" (__imp_?_Init@locale@std@@CAPAV_Locimp@12@_N@Z)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class std::locale const & __cdecl std::locale::classic(void)" (__imp_?classic@locale@std@@SAABV12@XZ)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) bool __cdecl std::uncaught_exception(void)" (__imp_?uncaught_exception@std@@YA_NXZ)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) unsigned long __cdecl std::_Winerror_message(unsigned long,char *,unsigned long)" (__imp_?_Winerror_message@std@@YAKKPADK@Z)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) __int64 const std::_BADOFF" (__imp_?_BADOFF@std@@3_JB)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) class std::basic_ostream<char,struct std::char_traits<char> > std::cerr" (__imp_?cerr@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) int __cdecl std::_Winerror_map(int)" (__imp_?_Winerror_map@std@@YAHH@Z)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) void __cdecl std::_Throw_C_error(int)" (__imp_?_Throw_C_error@std@@YAXH@Z)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "void __cdecl std::_Facet_Register(class std::_Facet_base *)" (?_Facet_Register@std@@YAXPAV_Facet_base@1@@Z)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class std::locale::id std::ctype<char>::id" (__imp_?id@?$ctype@D@std@@2V0locale@2@A)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) char const * __cdecl std::_Syserror_map(int)" (__imp_?_Syserror_map@std@@YAPBDH@Z)
1>wsclient.obj : error LNK2001: 无法解析的外部符号 __imp___Mtx_destroy_in_situ
1>wsclient.obj : error LNK2001: 无法解析的外部符号 __imp____std_type_info_compare
1>wsclient.obj : error LNK2001: 无法解析的外部符号 __imp___Mtx_lock
1>wsclient.obj : error LNK2001: 无法解析的外部符号 __imp___Mtx_init_in_situ
1>wsclient.obj : error LNK2001: 无法解析的外部符号 __imp___Query_perf_counter
1>wsclient.obj : error LNK2001: 无法解析的外部符号 __imp___Mtx_unlock

**Comment by mingkuang-Chuyu** [comment]
是的…… 暂时不可以用 msvcpt 的一些东西，不过这些问题暂时可以用代码解决，就是 去除iostream的依赖。CRT本身有函数可以实现iostream的功能。

**Comment by hzqst** [comment]
我自己写肯定不会随便用iostream的东西的。。关键这是第三方库。。。(websocketpp)

**Comment by mingkuang-Chuyu** [comment]
其实我建议你修改下库…… 把 iostream的调用全部换成 CRT函数调用。这样至少可以减少 80KB~ 120KB的程序体积。另外 iostream 都有对应的CRT实现，所以转换下应该还是可以接受的。

**Comment by mingkuang-Chuyu** [comment]
Hi，VC-LTL 2.0 已经发布，建议你重新在编译试试。已经添加了大量C++类库支持

**Comment by mingkuang-Chuyu** [comment]
如有问题还请及时反馈
