### ISSUE TITLE
無法使用ANTLR4

### ISSUE THREAD

**Issue by stevefan1999-personal** [Chuyu-Team/VC-LTL#60]
**bug标题（Describe the bug）**
同最简洁语言概括此BUG。

如果ANTLR用在動態鏈接版本，由於它用了本地版本的vcruntime而不是msvcrt，因此存在兩個CRT堆空間，導致堆內存管理混亂，從而令operator delete出現heap corruption。

**如何重现此问题？（To Reproduce）**
1. 構建一個含以上所有情況的軟件即可

**预期行为（Expected behavior）**
正常情况应该是怎么样的？

正常的執行我寫的parser =_=

**相关截图（Screenshots）**
相关错误截图，截图最好大一点。
N/A

**环境信息：（Information）**
 - OS: Windows 10
 - VC-LTL Version: 目前最新
 - VC Tools Version: 目前最新
 - UCRT Version: 目前最新
 - Platform: x64

**其他信息（Additional context）**
其他有关于这个问题的内容。
我用vcpkg裝的antlr4-runtime，static link情況未知

**Comment by mingkuang-Chuyu** [comment]
虽然你提供的信息很不全，特别是都没有提供示例代码。

不过你的问题我觉得应该是再说   A 模块 申请了 内存 让 B 模块去释放。

如果真是这样，那么就是你自己的问题了。

如果你一定要这样做，那么 就让 A、B二个模块使用相同的 VC库。VC-LTL也支持 vcpkg，你可以将 vcpkg 整合下 VC-LTL，然后编译一份  VC-LTL编译的 antlr4-runtime。

这是我写的文章
https://zhuanlan.zhihu.com/p/60369929

**Comment by mingkuang-Chuyu** [comment]
由于反馈者长时间没有回应，另外感觉也不像是问题，关闭此问题。
