### ISSUE TITLE
使用/Zc:threadSafeInit-后依然会产生TLS段

### ISSUE THREAD

**Issue by gmsj0001** [Chuyu-Team/VC-LTL#61]
似乎在不使用任何TLS依赖功能时（不使用__declspec(thread)且指定/Zc:threadSafeInit-），VC-LTL依然会链接TLS段（貌似在_invalid_parameter_advanced中引用）
不使用VC-LTL好像就不会生成。

**Comment by mingkuang-Chuyu** [comment]
符合预期。
