### ISSUE TITLE
14.28.29333工具集中的STL不完全支持Windows XP

### ISSUE THREAD

**Issue by mingkuang-Chuyu** [Chuyu-Team/VC-LTL#67]
此问题已知，我们正在评估是否有必要支持。

如果需要 请回复此问题。

**Comment by brian763** [comment]
望支持

**Comment by mingkuang-Chuyu** [comment]
VC-LTL不在处理此类问题，统一交给 YY-Thunks完成 低版本的 API兼容问题。

YY-Thunks v1.0.4-Beta2或者更高版本中，已经完成了所有ms工具集用到了不支持的API的Downlevle。

https://github.com/Chuyu-Team/YY-Thunks/releases/tag/v1.0.4-Beta2

如果你需哟支持XP，那么请与YY-Thunks结合使用。
