### ISSUE TITLE
ftelli64这个函数不能用

### ISSUE THREAD

**Issue by HwangBae** [Chuyu-Team/VC-LTL#7]
error LNK2001: unresolved external symbol __imp___ftelli64

**Comment by mingkuang-Chuyu** [comment]
谢谢，我会尽快修正

**Comment by mingkuang-Chuyu** [comment]
这个问题涉及多个VC库兼容问题，容我好好想想怎么解决。

**Comment by mingkuang-Chuyu** [comment]
感谢反馈，已经修正此问题。使用最新VC-LTL即可
