### ISSUE TITLE
Error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_LTL_StaticRelease' doesn't match value 'MT_StaticRelease'

### ISSUE THREAD

**Issue by UnlimitedChild** [Chuyu-Team/VC-LTL#70]
Hi,

**bug标题（Describe the bug）**
libcpmt.lib(xthrow.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_LTL_StaticRelease' doesn't match value 'MT_StaticRelease' in MyClass.obj
      Found "void (__cdecl* std::_Raise_handler)(class stdext::exception const &)" (?_Raise_handler@std@@3P6AXAEBVexception@stdext@@@ZEA)
        Referenced in MyClass.obj
        Loaded libcpmt.lib(raisehan.obj)
libcpmt.lib(raisehan.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_LTL_StaticRelease' doesn't match value 'MT_StaticRelease' in MyClass.obj

**如何重现此问题？（To Reproduce）**
An attempt was made to link an object file from another project.

**预期行为（Expected behavior）**
正常情况应该是怎么样的？
No link error.

**环境信息：（Information）**
 - Windows 10
 - VC-LTL Version - Most recent
 - VC Tools Version 14.28.29910
 - UCRT Version 10.0.19041.0
 - Platform x64

https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2038?view=msvc-160
Possible causes and solutions>
RuntimeLibrary Indicates the version of the C++ Standard Library and C runtime that's used by an app or library. Code that uses one version of the C++ Standard Library or C runtime is incompatible with code that uses a different version. For more information, see /MD, /MT, /LD (Use Run-Time Library).

Regards

**Comment by UnlimitedChild** [comment]
Please make a separate build with replacement of '**MT_LTL_StaticRelease**' value with '**MT_StaticRelease**', for those people who combine object modules from other compilers and work from the console.

**Comment by mingkuang-Chuyu** [comment]
all source codes need to be compiled with VC-LTL.

**Comment by UnlimitedChild** [comment]
> all source codes need to be compiled with VC-LTL
How to do it from the console ?! There are no other configuration options besides the console.

**Comment by mingkuang-Chuyu** [comment]
@UnlimitedChild https://github.com/Chuyu-Team/VC-LTL#33-using-vc-ltl-in-nmakecl
what about this?

**Comment by mingkuang-Chuyu** [comment]
这个问题看起来不是问题，看起来更像一个提问。

**Comment by UnlimitedChild** [comment]
I'm sorry, but this is not a solution. As I already said, a project without visual studio dependencies cannot be compiled due to this hack. You can't do this for many reasons, but even if you did so, then you should have an alternative build with the original name MT_StaticRelease, to maintain compatibility with projects that need to be compiled without system bindings. Unfortunately, it is impossible to use these libraries in a console project for this very reason.

**Comment by UnlimitedChild** [comment]
Better solution would be to use the /NODEFAULTLIB option, where you can exclude the standard libraries, and instead use yours with the LTL extension. In this case, such problems would not arise.

**Comment by mingkuang-Chuyu** [comment]
Your request is unreasonable. VC-LTL does not guarantee that the ABI is consistent with the completion of Microsoft. So you must recompile all static libraries.

**Comment by mingkuang-Chuyu** [comment]
There are also instructions in the document, if you need to use VC-LTL. Then all static libraries must be recompiled.

**Comment by mingkuang-Chuyu** [comment]
Please read the help document carefully.
