### ISSUE TITLE
Description of the project is not in English

### ISSUE THREAD

**Issue by UnlimitedChild** [Chuyu-Team/VC-LTL#71]
Hi,

**bug标题（Describe the bug）**
Severity	Code	Description	Project	File	Line	Suppression State
Error	LTL4000	VC-LTL不找不到lib文件，请从 https://github.com/Chuyu-Team/VC-LTL/releases/latest 下载完整二进制文件然后继续。	ucrt	Y:\VC-LTL\VC-LTL-master\VC-LTL-master\Config\config.props	221	

How to deal with a project if nothing is clear?

**Comment by mingkuang-Chuyu** [comment]
you can use Nuget(in 3.1.1.1.).

the VC-LTL nuget version is easy to use.

**Comment by UnlimitedChild** [comment]
Visual studio reports that it cannot display characters in the selected encoding. All Chinese characters are displayed as questions.

Y:\VC-LTL\VC-LTL-master\Config\config.props(214,5): warning LTL2002: VC-LTL???  ??,??????VC-LTL? [Y:\VC-LTL\VC-L
       TL-master\src\14.21.27702\Build\stl\stl.vcxproj]

In addition, it is not clear what is meant in the package settings from https://www.nuget.org/

![Property Pages](https://user-images.githubusercontent.com/16466330/120321998-3c019200-c2e4-11eb-8eef-52f87e1cfec6.jpg)

Not very user friendly.

**Comment by mingkuang-Chuyu** [comment]
we consider adding some English notes.

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL/releases/tag/v4.1.3-Beta1
