### ISSUE TITLE
The project cannot be compiled

### ISSUE THREAD

**Issue by UnlimitedChild** [Chuyu-Team/VC-LTL#72]
Hi,

the project cannot be compiled ...

**bug标题（Describe the bug）**
error : Designtime build failed for project 'Y:\VC-LTL\VC-LTL-master\VC-LTL-master\src\14.28.29333\Build\ConcRT\ConcRT.vcxproj' configuration 'Static_WinXP_Spectre|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.

100>  ◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆
100>  
100>  VC-LTL Path      : Y:\VC-LTL\VC-LTL-master\VC-LTL-master\
100>  VC Tools Version : 14.28.29333
100>  UCRT Version     : 10.0.19041.0
100>  Platform         : x64
100>  Using VC-LTL Vista Advanced Mode
100>Y:\VC-LTL\VC-LTL-master\VC-LTL-master\Config\config.props(221,5): error LTL4000: VC-LTL不找不到lib文件，请从 https://github.com/Chuyu-Team/VC-LTL/releases/latest 下载完整二进制文件然后继续。
100>Done building project "stl.vcxproj" -- FAILED.
106>------ Rebuild All started: Project: vcruntime (14.28.29910\vcruntime), Configuration: Static x64 ------

And this is how it looks with every project...

**Comment by mingkuang-Chuyu** [comment]
No need to compile it, we provide binary files.

If you must do this, then please download "VC-LTL-BaseBinary.7z". 
Then unzip it to the source code directory of VC-LTL.
Then execute the following command:
```
MSBuild.exe -m "XXXXXXXX\VC-LTL\src\Build.proj"
```

**Comment by UnlimitedChild** [comment]
> No need to compile it, we provide binary files.
> 
> If you must do this, then please download "VC-LTL-BaseBinary.7z".
> Then unzip it to the source code directory of VC-LTL.
> Then execute the following command:
> 
> ```
> MSBuild.exe -m "XXXXXXXX\VC-LTL\src\Build.proj"
> ```


Y:\VC-LTL\VC-LTL-master\src>MSBuild.exe -m "Y:\VC-LTL\VC-LTL-master\src\Build.proj"
Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 18.05.2021 12:18:15.
     1>Project "Y:\VC-LTL\VC-LTL-master\src\Build.proj" on node 1 (default targets).
     1>Y:\VC-LTL\VC-LTL-master\src\Build.proj(21,3): error MSB4019: The imported project "Y:\VC-LTL\VC-LTL-master\src\u
       crt\Build.proj" was not found. Confirm that the expression in the Import declaration "Y:\VC-LTL\VC-LTL-master\sr
       c\\ucrt\Build.proj" is correct, and that the file exists on disk.
     1>Done Building Project "Y:\VC-LTL\VC-LTL-master\src\Build.proj" (default targets) -- FAILED.

Build FAILED.

       "Y:\VC-LTL\VC-LTL-master\src\Build.proj" (default target) (1) ->
         Y:\VC-LTL\VC-LTL-master\src\Build.proj(21,3): error MSB4019: The imported project "Y:\VC-LTL\VC-LTL-master\src
       \ucrt\Build.proj" was not found. Confirm that the expression in the Import declaration "Y:\VC-LTL\VC-LTL-master\
       src\\ucrt\Build.proj" is correct, and that the file exists on disk.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.01

**Comment by mingkuang-Chuyu** [comment]
@UnlimitedChild  please retry.

https://github.com/Chuyu-Team/VC-LTL/commit/9cf964a84093861e45af417a33084e824cde151c

**Comment by mingkuang-Chuyu** [comment]
已经修复，用户没有继续提问。

**Comment by UnlimitedChild** [comment]
> No need to compile it, we provide binary files.
> 
> If you must do this, then please download "VC-LTL-BaseBinary.7z".
> Then unzip it to the source code directory of VC-LTL.
> Then execute the following command:
> 
> ```
> MSBuild.exe -m "XXXXXXXX\VC-LTL\src\Build.proj"
> ```

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targ
       ets(439,5): error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. T
       o build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgra
       de to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then select
       ing "Retarget solution". [Y:\VC-LTL\VC-LTL-master\src\14.11.25503\Build\ConcRT\ConcRT.vcxproj]
    23>Done Building Project "Y:\VC-LTL\VC-LTL-master\src\14.11.25503\Build\ConcRT\ConcRT.vcxproj" (default targets) --
        FAILED.

After finishing the retargeting of the project, then a lot of errors arise.

Y:\VC-LTL\VC-LTL-master\src\14.21.27702\stl\xlock.cpp(21,8): error C2665: 'InterlockedIncrement': none of the 3
       overloads could convert all the argument types [Y:\VC-LTL\VC-LTL-master\src\14.21.27702\Build\stl\stl.vcxproj]
       C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9560,1): message : could be 'unsigned _
       _int64 InterlockedIncrement(volatile unsigned __int64 *)' (compiling source file ..\..\stl\xlock.cpp) [Y:\VC-LTL
       \VC-LTL-master\src\14.21.27702\Build\stl\stl.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targ
       ets(486,5): error MSB8040: Spectre-mitigated libraries are required for this project. Install them from the Visu
       al Studio installer (Individual components tab) for any toolsets and architectures being used. Learn more: https
       ://aka.ms/Ofhn4c [Y:\VC-LTL\VC-LTL-master\src\14.25.28610\Build\vcruntime\vcruntime.vcxproj]
    70>Done Building Project "Y:\VC-LTL\VC-LTL-master\src\14.25.28610\Build\vcruntime\vcruntime.vcxproj" (default targe
       ts) -- FAILED.

LINK : fatal error LNK1181: cannot open input file 'Y:\VC-LTL\VC-LTL-master\src\i386\objs.lib' [Y:\VC-LTL\VC-LTL
       -master\src\14.25.28610\Build\vcruntime\vcruntime.vcxproj]
    70>Done Building Project "Y:\VC-LTL\VC-LTL-master\src\14.25.28610\Build\vcruntime\vcruntime.vcxproj" (default targe
       ts) -- FAILED.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.tar
       gets(241,5): error MSB8066: Custom build for '..\..\..\arm\exception.asm' exited with code 9009. [Y:\VC-LTL\VC-L
       TL-master\src\14.26.28801\Build\ltlbuild\ltlbuild.vcxproj]
    72>Done Building Project "Y:\VC-LTL\VC-LTL-master\src\14.26.28801\Build\ltlbuild\ltlbuild.vcxproj" (default targets
       ) -- FAILED.

     5>Y:\VC-LTL\VC-LTL-master\src\14.0.23918\stl\excptptr.cpp(111,13): error C3861: 'CT_COPYFUNC': identifier not found [Y:\VC-LTL\VC-LTL-master\src\14.0.23918\Build\stl\stl.vcxproj]
         raisehan.cpp
     5>Y:\VC-LTL\VC-LTL-master\src\14.0.23918\stl\excptptr.cpp(138,1): error C3861: 'CT_COPYFUNC': identifier not found [Y:\VC-LTL\VC-LTL-master\src\14.0.23918\Build\stl\stl.vcxproj]
     5>Y:\VC-LTL\VC-LTL-master\src\14.0.23918\stl\excptptr.cpp(138,1): error C2065: 'CT_COPYFUNC': undeclared identifier [Y:\VC-LTL\VC-LTL-master\src\14.0.23918\Build\stl\stl.vcxproj]
     5>Y:\VC-LTL\VC-LTL-master\src\14.0.23918\stl\excptptr.cpp(150,1): error C3861: 'CT_COPYFUNC': identifier not found [Y:\VC-LTL\VC-LTL-master\src\14.0.23918\Build\stl\stl.vcxproj]
     5>Y:\VC-LTL\VC-LTL-master\src\14.0.23918\stl\excptptr.cpp(150,1): error C2065: 'CT_COPYFUNC': undeclared identifier [Y:\VC-LTL\VC-LTL-master\src\14.0.23918\Build\stl\stl.vcxproj]
     5>Y:\VC-LTL\VC-LTL-master\src\14.0.23918\stl\excptptr.cpp(396,17): error C3861: 'THROW_COUNT': identifier not found [Y:\VC-LTL\VC-LTL-master\src\14.0.23918\Build\stl\stl.vcxproj]
     5>Y:\VC-LTL\VC-LTL-master\src\14.0.23918\stl\excptptr.cpp(409,39): error C3861: 'THROW_CTLIST': identifier not found [Y:\VC-LTL\VC-LTL-master\src\14.0.23918\Build\stl\stl.vcxproj]
     5>Y:\VC-LTL\VC-LTL-master\src\14.0.23918\stl\excptptr.cpp(461,43): error C3861: 'THROW_CTLIST': identifier not found [Y:\VC-LTL\VC-LTL-master\src\14.0.23918\Build\stl\stl.vcxproj]
     5>Y:\VC-LTL\VC-LTL-master\src\14.0.23918\stl\excptptr.cpp(475,1): warning C4312: 'type cast': conversion from 'const PMFN' to 'void (__cdecl *)(PVOID)' of greater size [Y:\VC-LTL\VC-LTL-master\src\14.0.23918\Build\stl\stl.vcxproj]
     5>Y:\VC-LTL\VC-LTL-master\src\14.0.23918\stl\excptptr.cpp(532,17): error C3861: 'THROW_COUNT': identifier not found [Y:\VC-LTL\VC-LTL-master\src\14.0.23918\Build\stl\stl.vcxproj]
     5>Y:\VC-LTL\VC-LTL-master\src\14.0.23918\stl\excptptr.cpp(544,39): error C3861: 'THROW_CTLIST': identifier not found [Y:\VC-LTL\VC-LTL-master\src\14.0.23918\Build\stl\stl.vcxproj]

     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9564,32): error C2065: 'InterlockedIncrement64': undeclared identifier (compiling source file ..\..\stl\fiopen.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9596,32): error C2065: 'InterlockedDecrement64': undeclared identifier (compiling source file ..\..\stl\fiopen.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9632,31): error C3861: 'InterlockedExchange64': identifier not found (compiling source file ..\..\stl\fiopen.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9686,31): error C3861: 'InterlockedExchangeAdd64': identifier not found (compiling source file ..\..\stl\fiopen.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9696,31): error C3861: 'InterlockedExchangeAdd64': identifier not found (compiling source file ..\..\stl\fiopen.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9743,31): error C3861: 'InterlockedAnd64': identifier not found (compiling source file ..\..\stl\fiopen.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9564,32): error C2065: 'InterlockedIncrement64': undeclared identifier (compiling source file ..\..\stl\filesys.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9753,31): error C3861: 'InterlockedOr64': identifier not found (compiling source file ..\..\stl\fiopen.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9596,32): error C2065: 'InterlockedDecrement64': undeclared identifier (compiling source file ..\..\stl\filesys.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9763,31): error C3861: 'InterlockedXor64': identifier not found (compiling source file ..\..\stl\fiopen.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9632,31): error C3861: 'InterlockedExchange64': identifier not found (compiling source file ..\..\stl\filesys.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9686,31): error C3861: 'InterlockedExchangeAdd64': identifier not found (compiling source file ..\..\stl\filesys.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9696,31): error C3861: 'InterlockedExchangeAdd64': identifier not found (compiling source file ..\..\stl\filesys.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9743,31): error C3861: 'InterlockedAnd64': identifier not found (compiling source file ..\..\stl\filesys.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9753,31): error C3861: 'InterlockedOr64': identifier not found (compiling source file ..\..\stl\filesys.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9763,31): error C3861: 'InterlockedXor64': identifier not found (compiling source file ..\..\stl\filesys.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>ClCompile:
         ppltasks.cpp
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9564,32): error C2065: 'InterlockedIncrement64': undeclared identifier (compiling source file ..\..\stl\iosptrs.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9596,32): error C2065: 'InterlockedDecrement64': undeclared identifier (compiling source file ..\..\stl\iosptrs.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>ClCompile:
         wcerr.cpp
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9632,31): error C3861: 'InterlockedExchange64': identifier not found (compiling source file ..\..\stl\iosptrs.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9686,31): error C3861: 'InterlockedExchangeAdd64': identifier not found (compiling source file ..\..\stl\iosptrs.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9696,31): error C3861: 'InterlockedExchangeAdd64': identifier not found (compiling source file ..\..\stl\iosptrs.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9743,31): error C3861: 'InterlockedAnd64': identifier not found (compiling source file ..\..\stl\iosptrs.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9753,31): error C3861: 'InterlockedOr64': identifier not found (compiling source file ..\..\stl\iosptrs.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9763,31): error C3861: 'InterlockedXor64': identifier not found (compiling source file ..\..\stl\iosptrs.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9564,32): error C2065: 'InterlockedIncrement64': undeclared identifier (compiling source file ..\..\stl\locale.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9596,32): error C2065: 'InterlockedDecrement64': undeclared identifier (compiling source file ..\..\stl\locale.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9632,31): error C3861: 'InterlockedExchange64': identifier not found (compiling source file ..\..\stl\locale.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9686,31): error C3861: 'InterlockedExchangeAdd64': identifier not found (compiling source file ..\..\stl\locale.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9696,31): error C3861: 'InterlockedExchangeAdd64': identifier not found (compiling source file ..\..\stl\locale.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9743,31): error C3861: 'InterlockedAnd64': identifier not found (compiling source file ..\..\stl\locale.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9753,31): error C3861: 'InterlockedOr64': identifier not found (compiling source file ..\..\stl\locale.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9763,31): error C3861: 'InterlockedXor64': identifier not found (compiling source file ..\..\stl\locale.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
       ClCompile:
         wcin.cpp
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9564,32): error C2065: 'InterlockedIncrement64': undeclared identifier (compiling source file ..\..\stl\locale0.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9596,32): error C2065: 'InterlockedDecrement64': undeclared identifier (compiling source file ..\..\stl\locale0.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9632,31): error C3861: 'InterlockedExchange64': identifier not found (compiling source file ..\..\stl\locale0.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9686,31): error C3861: 'InterlockedExchangeAdd64': identifier not found (compiling source file ..\..\stl\locale0.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9696,31): error C3861: 'InterlockedExchangeAdd64': identifier not found (compiling source file ..\..\stl\locale0.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9743,31): error C3861: 'InterlockedAnd64': identifier not found (compiling source file ..\..\stl\locale0.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9753,31): error C3861: 'InterlockedOr64': identifier not found (compiling source file ..\..\stl\locale0.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9763,31): error C3861: 'InterlockedXor64': identifier not found (compiling source file ..\..\stl\locale0.cpp) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
       ClCompile:
         wclog.cpp
         wcout.cpp
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9564,32): error C2065: 'InterlockedIncrement64': undeclared identifier (compiling source file ..\..\stl\mutex.c) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9596,32): error C2065: 'InterlockedDecrement64': undeclared identifier (compiling source file ..\..\stl\mutex.c) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9632,31): error C3861: 'InterlockedExchange64': identifier not found (compiling source file ..\..\stl\mutex.c) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9686,31): error C3861: 'InterlockedExchangeAdd64': identifier not found (compiling source file ..\..\stl\mutex.c) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9696,31): error C3861: 'InterlockedExchangeAdd64': identifier not found (compiling source file ..\..\stl\mutex.c) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9743,31): error C3861: 'InterlockedAnd64': identifier not found (compiling source file ..\..\stl\mutex.c) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9753,31): error C3861: 'InterlockedOr64': identifier not found (compiling source file ..\..\stl\mutex.c) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
     9>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9763,31): error C3861: 'InterlockedXor64': identifier not found (compiling source file ..\..\stl\mutex.c) [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\stl\stl.vcxproj]
       ClCompile:

    10>Y:\VC-LTL\VC-LTL-master\src\14.0.24210\vcruntime\frame.cpp(2167,20): error C2039: 'pType': is not a member of '_s_HandlerType' [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\vcruntime\vcruntime.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include\ehdata.h(93): message : see declaration of '_s_HandlerType' [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\vcruntime\vcruntime.vcxproj]
    10>Y:\VC-LTL\VC-LTL-master\src\14.0.24210\vcruntime\frame.cpp(2170,13): error C3861: 'SET_HT_ISCOMPLUSEH': identifier not found [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\vcruntime\vcruntime.vcxproj]
    10>Y:\VC-LTL\VC-LTL-master\src\14.0.24210\vcruntime\frame.cpp(2173,61): error C2440: '=': cannot convert from 'const int []' to 'CatchableType *__unaligned const *' [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\vcruntime\vcruntime.vcxproj]
       Y:\VC-LTL\VC-LTL-master\src\14.0.24210\vcruntime\frame.cpp(2173,27): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\vcruntime\vcruntime.vcxproj]
    10>Y:\VC-LTL\VC-LTL-master\src\14.0.24210\vcruntime\frame.cpp(2337,57): error C2440: '=': cannot convert from 'const int []' to 'CatchableType *__unaligned const *' [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\vcruntime\vcruntime.vcxproj]
       Y:\VC-LTL\VC-LTL-master\src\14.0.24210\vcruntime\frame.cpp(2337,23): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\vcruntime\vcruntime.vcxproj]
    10>Y:\VC-LTL\VC-LTL-master\src\14.0.24210\vcruntime\frame.cpp(2445,53): error C2440: '=': cannot convert from 'const int []' to 'CatchableType *const *' [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\vcruntime\vcruntime.vcxproj]
       Y:\VC-LTL\VC-LTL-master\src\14.0.24210\vcruntime\frame.cpp(2445,19): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast [Y:\VC-LTL\VC-LTL-master\src\14.0.24210\Build\vcruntime\vcruntime.vcxproj]
       ClCompile:

**Comment by mingkuang-Chuyu** [comment]
@UnlimitedChild This is your mistake.
