### ISSUE TITLE
升级 Visual Studio 16.10.0 后采用了 VC-LTL 的项目编译失败

### ISSUE THREAD

**Issue by MouriNaruto** [Chuyu-Team/VC-LTL#74]
![image](https://user-images.githubusercontent.com/10867563/119826214-604b2080-bf2a-11eb-9737-02b093c4c2a4.png)
![image](https://user-images.githubusercontent.com/10867563/119826238-66d99800-bf2a-11eb-9fe4-6c970c4b735b.png)

![image](https://user-images.githubusercontent.com/10867563/119826512-adc78d80-bf2a-11eb-8a17-6a30990a442e.png)

VS 包含目录计算正确
![image](https://user-images.githubusercontent.com/10867563/119826471-a1433500-bf2a-11eb-8533-5d8899634141.png)
但 MSBuild 包含目录计算有问题

**Comment by mingkuang-Chuyu** [comment]
4.1.2-Beta3
修复
