### ISSUE TITLE
代码中使用std::format时，编译报无法解析的外部符号 ___std_get_cvt@8(x86),__std_get_cvt(x64)

### ISSUE THREAD

**Issue by stsm85** [Chuyu-Team/VC-LTL#75]
**bug标题（Describe the bug）**
代码中使用std::format时，编译报错：
x86: 无法解析的外部符号 ___std_get_cvt@8
x64: 无法解析的外部符号 __std_get_cvt

**如何重现此问题？（To Reproduce）**

使用代码
auto base64str = std::format("123123{}", "asd");

**预期行为（Expected behavior）**

**相关截图（Screenshots）**

**环境信息：（Information）**
 - OS: Windows 7 SP1 x64
 - VC-LTL Version 4.1.3-Beta1
 - VC Tools Version 14.29.30037
 - UCRT Version 10.0.19041.0
 - Platform   x86 x64
 - 

**其他信息（Additional context）**

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/VC-LTL/releases/tag/v4.1.3-Beta2
