### ISSUE TITLE
Windows 11 (10.0.22000.51) + unicorn (sample_x86) + VC-LTL = crash

### ISSUE THREAD

**Issue by hzqst** [Chuyu-Team/VC-LTL#76]
**bug标题（Describe the bug）**

Windows 11 (10.0.22000.51) + unicorn (sample_x86) + VC-LTL = crash

**如何重现此问题？（To Reproduce）**

1、需要操作系统：Windows 11 (10.0.22000.51)，我只试了两台，其中有一台无法复现，另一台可以稳定复现。

2、https://github.com/unicorn-engine/unicorn 我试了2020年4月的版本，和最近的最新版本，套上VCLTL之后就可以复现，不套VCLTL无任何问题

3、需要给[unicorn.sln](https://github.com/unicorn-engine/unicorn/blob/master/msvc/unicorn.sln)中的所有项目套上`VC-LTL helper for Visual Studio.props`，并且以x64 Release方式编译unicorn.sln中的sample_x86项目

4、在win11系统中cmd运行sample_x86

刚开始运行第一个测试，就会陷入几秒钟的停顿，然后crash

![12 @~_) CK4KIRC319S9}GH](https://user-images.githubusercontent.com/12287588/125452251-e45306ae-66e9-465d-ae71-f6020070e0f1.png)

**预期行为（Expected behavior）**

正常应该如图所示跑完所有测试
![~VDRI62I7USXL8I~MYJ2AOJ](https://user-images.githubusercontent.com/12287588/125452127-d54ef41f-bf97-4dae-a417-c25465eb667f.jpg)

**环境信息：（Information）**
 - OS: Windows 11 (10.0.22000.51)
 - VC-LTL Version 2021年3月9日的版本
 - VC Tools Version : 14.16.27023
 - UCRT Version     : 10.0.10240.0
 - Platform         : x64

**其他信息（Additional context）**

需要使用稳定复现crash的那台机器，可以群里找我远程

**Comment by hzqst** [comment]
更新至VCLTLv4.1.3后不再crash 问题解决 thx

**Comment by mingkuang-Chuyu** [comment]
既然新版本没有这样的问题，那么我就拉入无效反馈了。

其实我一脸懵，老版本与新版本看起来没有什么变化。
